# Generated by Django 4.0.4 on 2022-06-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_firm_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='about',
        ),
    ]
