# Generated by Django 4.0.5 on 2022-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_firm_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='User name')),
                ('cart_number', models.IntegerField(verbose_name='Cart number')),
                ('img', models.ImageField(upload_to='media', verbose_name='Cart image')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
    ]
