# Generated by Django 4.0.5 on 2022-06-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usercarts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercarts',
            name='img',
        ),
    ]
