# Generated by Django 4.0.5 on 2022-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_usercarts_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercarts',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Image'),
        ),
    ]
