# Generated by Django 4.0.5 on 2022-06-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_usercarts_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercarts',
            name='img',
        ),
    ]
